name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    
    - name: Build and push auth service
      run: |
        cd services/auth
        docker build -t $DOCKER_HUB_USERNAME/auth-service:latest .
        docker push $DOCKER_HUB_USERNAME/auth-service:latest
    
    - name: Build and push blog service
      run: |
        cd services/blog
        docker build -t $DOCKER_HUB_USERNAME/blog-service:latest .
        docker push $DOCKER_HUB_USERNAME/blog-service:latest
    
    - name: Build and push analytics service
      run: |
        cd services/analytics
        docker build -t $DOCKER_HUB_USERNAME/analytics-service:latest .
        docker push $DOCKER_HUB_USERNAME/analytics-service:latest
    
    - name: Build and push apache proxy
      run: |
        cd apache
        docker build -t $DOCKER_HUB_USERNAME/apache-proxy:latest .
        docker push $DOCKER_HUB_USERNAME/apache-proxy:latest
    
  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=./kubeconfig.yaml
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/auth/
        kubectl apply -f kubernetes/blog/
        kubectl apply -f kubernetes/analytics/
        kubectl apply -f kubernetes/apache/
